# docker가 설치된 경우
# 다음 명령어를 터미널에 입력하면 5432번으로 postgresql이 서비스됩니다.

# docker-compose -f postgresql-docker-compose.yml up

# 이 경우 데이터베이스는 접속 후 만들어줘야 합니다.

version: '3.1'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'test' # id
      POSTGRES_PASSWORD: 'test' # pw
    restart: always
